### ISSUE TITLE
Video posts support

### ISSUE THREAD

**Issue by sobstel** [sobstel/calmbook#3]
eg. https://www.facebook.com/FacebookPolska/

**Comment by malczak** [comment]
This one is a bummer
- fb is using streams for video so seems like we cannot parse video url from html
- video embedding  could be an answer (see research on [video-research](https://github.com/sobstel/calmbook/tree/video-research) branch)

📣@sobstel

**Comment by sobstel** [comment]
Whatever works :tm: 

Please do the PR from this and I'll test at my side.

**Comment by malczak** [comment]
Works. The solution was to use FB.XFBML.parse which is added to window after loading initial embed script ([PR](https://github.com/sobstel/calmbook/pull/10))

**Comment by malczak** [comment]
Closed with #10
