### ISSUE TITLE
Load more posts

### ISSUE THREAD

**Issue by malczak** [sobstel/calmbook#6]
Add support for lazy loading more posts.

**Comment by malczak** [comment]
Not valid. Calmbook is all about seeing 'latest news' not about creating alternative FB wall scroller

**Comment by sobstel** [comment]
Agreed. [Pull-to-refresh infinity pool](https://medium.com/make-time/distractions-are-a-nuisance-but-infinity-pools-are-the-real-problem-e84122d62c0c) is definitely something I'd like to avoid.
